### PR TITLE
Alessio unit test gutenberg media and helpers functions

### PR DESCRIPTION
**Pull request by cpalessio96**
### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:
Add tests for gutenberg, media library and helpers functions

### CODE REVIEW

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/MediaLibrary/MediaLibraryExtented.php  35
+ includes/MediaLibrary/ListingSubtitles.php  65
+ includes/Gutenberg/TranscriptionBlock.php  47
+ includes/Gutenberg/VideoBlock.php  52
         

Complexity increasing per file
==============================
- tests/test-video-block.php  1
- tests/test-listing-subtitle.php  1
- tests/test-gutenberg-transcription-block.php  1
- tests/test-media-library-extented.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6138559&bid=20070019)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test-gutenberg-transcription-block.php  1
- tests/test-listing-subtitle.php  1
- tests/test-transcriptions-extends.php  1
- tests/test-media-library-extented.php  1
- tests/test-video-block.php  1
- tests/test-helpers.php  1
- tests/test-invoice-helpers.php  2
- tests/test-vimeo-helpers.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6138559&bid=20070019)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/test-media-library-extented.php  1
- tests/test-gutenberg-transcription-block.php  1
- tests/test-video-block.php  1
- tests/test-helpers.php  1
- tests/test-listing-subtitle.php  1
- tests/test-invoice-helpers.php  2
- tests/test-vimeo-helpers.php  1
- tests/test-transcriptions-extends.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6138559&bid=20070019)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/MediaLibrary/ListingSubtitles.php  65
+ includes/MediaLibrary/TrascriptionsExtends.php  61
+ includes/Gutenberg/VideoBlock.php  52
+ includes/Gutenberg/TranscriptionBlock.php  47
+ includes/Utils/InvoiceHelper.php  29
+ includes/Utils/VimeoHelper.php  100
+ includes/MediaLibrary/MediaLibraryExtented.php  35
+ includes/Helpers.php  71
         

Complexity increasing per file
==============================
- tests/test-listing-subtitle.php  1
- tests/test-video-block.php  1
- tests/test-media-library-extented.php  1
- tests/test-vimeo-helpers.php  1
- tests/test-transcriptions-extends.php  1
- tests/test-invoice-helpers.php  2
- tests/test-gutenberg-transcription-block.php  1
- tests/test-helpers.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6138559&bid=20070019)

**Review by HyprCoder — APPROVED** [review]

**Pull request merged**
