### PR TITLE
Alessio add all languages support

### LINKED ISSUE #386: Add support for all languages supported by aws transcribe
## Feature request
Add support for this languages:

- Gulf Arabic

- Modern Standard Arabic

- Chinese Mandarin - Mainland

- Dutch

- Australian English

- British English

- Indian English 

- Irish English

- Scottish English

- US English

- Welsh English

- Spanish

- US Spanish

- French

- Canadian French

- Farsi

- German

- Swiss German

- Hebrew

- Indian Hindi

- Indonesian

- Italian

- Japanese

- Korean

- Malay

- Portuguese 

- Brazilian Portuguese

- Russian

- Tamil

- Telugu

- Turkish

### Feature description

Add support for all languages supported by aws for internal video transcriptions

### How the feature is useful

increase the supported languages for transcription

### PR DESCRIPTION
**Pull request by cpalessio96**
### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:
Add all languages supported by aws transcribe for internal video

Closes #386  .

### CODE REVIEW

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/Gutenberg/VideoBlock.php  1
+ includes/MediaLibrary/MediaLibraryExtented.php  1
+ includes/Helpers.php  14
         

Coverage decreased per file
===========================
- includes/Api/ApiRequest.php  -1
         

Complexity increasing per file
==============================
- src/block/labels.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6202351&bid=20229518)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/block/labels.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6202351&bid=20229518)

**Review by SalvoCozzubo — APPROVED** [review]

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/block/labels.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6202351&bid=20229518)

**Review by HyprCoder — APPROVED** [review]

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/block/labels.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6202351&bid=20229518)

**Pull request merged**
