### PR TITLE
Alessio vimeo classic editor

### LINKED ISSUE #360: Add vimeo support to classic editor
## Feature request
Add support to classic editor for get vimeo transcription
### Feature description
Get vimeo transcription on classic editor like as it was done on youtube

### PR DESCRIPTION
**Pull request by cpalessio96**
### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:
Add support to classic editor

Closes #360  .

Depends on #362 .

### CODE REVIEW

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/Api/ApiGetTranscript.php  3
         

Coverage decreased per file
===========================
- includes/Core/Sources/YouTube.php  -4
         

Complexity increasing per file
==============================
- src/block/EmbedControlPanel.js  12
- src/block/EmbedBlock.js  3
- includes/Utils/VimeoHelper.php  1
- tests/test-vimeo.php  1
- includes/Api/ApiGetTranscript.php  2
- includes/Core/Sources/Vimeo.php  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6124268&bid=20035368)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/block/EmbedBlock.js  3
- tests/test-vimeo.php  1
- includes/Api/ApiGetTranscript.php  2
- src/block/EmbedControlPanel.js  12
- includes/Utils/VimeoHelper.php  1
- includes/Core/Sources/Vimeo.php  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6124268&bid=20035368)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/block/EmbedControlPanel.js  12
- tests/test-vimeo.php  1
- includes/Core/Sources/Vimeo.php  5
- src/block/EmbedBlock.js  3
- includes/Utils/VimeoHelper.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6124268&bid=20035368)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/block/EmbedBlock.js  3
- tests/test-vimeo.php  1
- src/block/EmbedControlPanel.js  12
- includes/Core/Sources/Vimeo.php  5
- includes/Utils/VimeoHelper.php  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6124268&bid=20035368)

**Review by HyprCoder — DISMISSED** [review]

**Review by HyprCoder — APPROVED** [review]

**Pull request merged**
