### PR TITLE
Alessio remove old get transcript functionality

### LINKED ISSUE #361: Remove old functionality "get transcript"
## Feature request
Remove old feature for get transcription on transcript post type page,
the feature is not used and can be confusing with the new feature that implements vimeo support

### PR DESCRIPTION
**Pull request by cpalessio96**
### All Submissions:

*   [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
*   [x] Does your code has proper inline documentation? 

### Changes proposed in this Pull Request:
Removed old functionality

Depends on #362 
Closes #361  .

### CODE REVIEW

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage increased per file
===========================
+ includes/Api/ApiGetTranscript.php  20
         

Coverage decreased per file
===========================
- includes/Core/CustomPostTypes/Transcript.php  -1
- includes/Core/Sources/YouTube.php  -19
         

Complexity increasing per file
==============================
- src/block/EmbedControlPanel.js  12
- tests/test-vimeo.php  1
- includes/Core/Sources/Vimeo.php  5
- src/block/EmbedBlock.js  3
- includes/Api/ApiGetTranscript.php  2
- includes/Utils/VimeoHelper.php  1
         

Complexity decreasing per file
==============================
+ includes/Core/CustomPostTypes/Transcript.php  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6120222&bid=20026245)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- includes/Api/ApiGetTranscript.php  2
- includes/Core/Sources/Vimeo.php  5
- src/block/EmbedBlock.js  3
- src/block/EmbedControlPanel.js  12
- tests/test-vimeo.php  1
- includes/Utils/VimeoHelper.php  1
         

Complexity decreasing per file
==============================
+ includes/Core/CustomPostTypes/Transcript.php  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6120222&bid=20026245)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/block/EmbedBlock.js  3
- tests/test-vimeo.php  1
- src/block/EmbedControlPanel.js  12
- includes/Utils/VimeoHelper.php  1
- includes/Core/Sources/Vimeo.php  5
- includes/Api/ApiGetTranscript.php  2
         

Complexity decreasing per file
==============================
+ includes/Core/CustomPostTypes/Transcript.php  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6120222&bid=20026245)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- includes/Core/Sources/Vimeo.php  5
- includes/Utils/VimeoHelper.php  1
- src/block/EmbedControlPanel.js  12
- src/block/EmbedBlock.js  3
- tests/test-vimeo.php  1
         

Complexity decreasing per file
==============================
+ includes/Core/CustomPostTypes/Transcript.php  -3
+ includes/Api/ApiGetTranscript.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6120222&bid=20026245)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- includes/Utils/VimeoHelper.php  1
- src/block/EmbedControlPanel.js  12
- tests/test-vimeo.php  1
- includes/Core/Sources/Vimeo.php  5
- src/block/EmbedBlock.js  3
         

Complexity decreasing per file
==============================
+ includes/Core/CustomPostTypes/Transcript.php  -3
+ includes/Api/ApiGetTranscript.php  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6120222&bid=20026245)

**Comment by GiuseppeIuculano** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ includes/Api/ApiGetTranscript.php  -1
+ includes/Core/CustomPostTypes/Transcript.php  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/CTMobi/Wubtitle-Wordpress-Plugin/pullRequest?prid=6120222&bid=20026245)

**Review by HyprCoder — APPROVED** [review]

**Pull request merged**
